### ISSUE TITLE
zeroconf exception when running two IS-04 v1.2 tests at once

### ISSUE THREAD

**Issue by billt-hlit** [bbc/nmos-testing#11]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hbv-bld1/bt/git/nmos-testing/nmos-test.py", line 134, in index_page
    result = test_obj.run_tests()
  File "/home/hbv-bld1/bt/git/nmos-testing/GenericTest.py", line 90, in run_tests
    self.execute_tests()
  File "/home/hbv-bld1/bt/git/nmos-testing/IS0401Test.py", line 44, in execute_tests
    super(IS0401Test, self).execute_tests()
  File "/home/hbv-bld1/bt/git/nmos-testing/GenericTest.py", line 86, in execute_tests
    self.result.append(method())
  File "/home/hbv-bld1/bt/git/nmos-testing/IS0401Test.py", line 65, in test_01
    zeroconf.register_service(info)
  File "/usr/lib/python3/dist-packages/zeroconf.py", line 1427, in register_service
    self.check_service(info)
  File "/usr/lib/python3/dist-packages/zeroconf.py", line 1533, in check_service
    raise NonUniqueNameException
zeroconf.NonUniqueNameException

**Comment by garethsb-sony** [comment]
Don't do that? ;-)

**Comment by andrewbonney** [comment]
Having just checked it's actually already on the README: "The IS-04 Node tests create a mock registry on the network. It is critical that these are only run in isolated network segments away from production Nodes and registries. Only one Node can be tested at a single time."

**Comment by billt-hlit** [comment]
Well, the reason I keep bumping into this problem is that, if the tests hang (far too frequent because of mDNS problems) and I restart it, the restarted test is a second test as far as the test harness is concerned -- hence the exception.

That said, it's not a difficult problem to work around, although it's going to make it hard to use the test suite at a workshop or other gathering.

In any event, a friendly error message might be an improvement over the exception backtrace....

**Comment by andrewbonney** [comment]
That sounds doable. I'll take a look.

**Comment by billt-hlit** [comment]
I just semi-voluntarily tested this change. Very elegant. Thank you!
