### ISSUE TITLE
IS-05 test failure: simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by billt-hlit** [bbc/nmos-testing#2]
I tried running the IS-05 tests and got the following traceback (I'll try to add more data as I find it):

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/flask/app.py", line 1997, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/lib/python3/dist-packages/flask/app.py", line 1985, in wsgi_app
        response = self.handle_exception(e)
      File "/usr/lib/python3/dist-packages/flask/app.py", line 1540, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/hbv-bld1/bt/git/nmos-testing/nmos-test.py", line 122, in index_page
        result = test_obj.run_tests()
      File "/home/hbv-bld1/bt/git/nmos-testing/GenericTest.py", line 75, in run_tests
        self.execute_tests()
      File "/home/hbv-bld1/bt/git/nmos-testing/GenericTest.py", line 65, in execute_tests
        self.result += self.basics()
      File "/home/hbv-bld1/bt/git/nmos-testing/GenericTest.py", line 178, in basics
        result = self.check_api_resource(resource, response_code, api)
      File "/home/hbv-bld1/bt/git/nmos-testing/GenericTest.py", line 229, in check_api_resource
        self.save_subresources(resource[0], response)
      File "/home/hbv-bld1/bt/git/nmos-testing/GenericTest.py", line 247, in save_subresources
        if isinstance(response.json(), list):
      File "/usr/lib/python3/dist-packages/requests/models.py", line 842, in json
        self.content.decode(encoding), **kwargs
      File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 516, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 374, in decode
        obj, end = self.raw_decode(s)
      File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 404, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by billt-hlit** [comment]
The Debian packaging information says:

 Metadata-Version: 1.1
 Name: simplejson
 Version: 3.10.0

**Comment by billt-hlit** [comment]
According to tcpdump, the last request-response pair in the interaction with the Node was

    GET /x-nmos/connection/v1.0/single/senders/fef711e5-da6b-5148-997c-5ceb5581cb4d/transportfile HTTP/1.1

followed by

    HTTP/1.1 307 Temporary Redirect
    Access-Control-Allow-Origin: *
    Access-Control-Expose-Headers: Location
    Content-Length: 0
    Location: http://10.10.138.104/sdp.dir/30HzVideo.sdp

Maybe the script doesn't handle the redirect correctly?

**Comment by andrewbonney** [comment]
I could potentially change these to catch the more general 'ValueError', but it might be less clear what's going on.

**Comment by andrewbonney** [comment]
Thanks. I'll close this for now, but it sounds like a good one to keep an eye out for anyone else experiencing.
